version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch_llmla
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearchdashboards_llmla
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch_llmla:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    ports:
      - 5601:5601
    expose:
      - "5601"
    networks:
      - opensearch-net

networks:
  opensearch-net:
