version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch_llmla
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - transport.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limits)
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data # Creates a volume called opensearch-data and attach it to the container
    ports:
      - 9200:9200 # Rest API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net:
