version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch_llmla
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearchdashboards_llmla
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200", "https://localhost:9200"]'
    ports:
      - 5601:5601
    expose:
      - "5601"
