name: Code Quality
run-name: Pull Requests / Push from ${{ github.ref }} to main, created by by ${{ github.actor }}. This action ensures that the code quality is maintained.

on:
  push:
  pull_request:
    branches: [main]
    paths: "**.py"

    jobs:
      pre-commit:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
              python-version: "3.11"
          - uses: pre-commit/action@v2.2.0
